name: Push trigger file

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0/4 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: |
          mkdir -p _trigger-file
          [ ! -e _trigger-file/_trigger_* ] || rm -R _trigger-file/_trigger_*
          touch _trigger-file/_trigger_$(date "+%Y-%m-%d_%H%M%S") # trigger file in source directory
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '_trigger-file'
          destination-github-username: 'philipp-baumann'
          destination-repository-name: 'ci-test-target-cp-file'
          user-email: baumann-philipp@protonmail.com
          target-branch: target_cp
          target-directory: _trigger_file
