name: Push trigger file to philipp-baumann/nixpkgs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: |
          mkdir -p _trigger-file_nixpkgs
          [ ! -e _trigger-file_nixpkgs/_trigger_* ] || rm -R _trigger-file_nixpkgs/_trigger_*
          touch _trigger-file_nixpkgs/_trigger_$(date "+%Y-%m-%d_%H%M%S") # trigger file in source directory
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_NIXPKGS }}
        with:
          source-directory: '_trigger-file'
          destination-github-username: 'philipp-baumann'
          destination-repository-name: 'nixpkgs'
          user-email: baumann-philipp@protonmail.com
          target-branch: r-daily-source
